In [21]:
import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:,.4f}".format)

In [22]:
df=pd.read_csv("../data/raw/Open database on global coal and metal mining/data/facilities.gpkg")
gdf=gpd.read_file("../data/raw/Open database on global coal and metal mining/data/facilities.gpkg")

In [24]:
print(gdf.head())

   facility_id             facility_name facility_other_names sub_site_name  \
0  COM00001.00                       777                  NaN           NaN
1  COM00002.00                 A Narrain                  NaN           NaN
2  COM00003.00                  Absaloka                  NaN           NaN
3  COM00004.00                      Abyz                  NaN           NaN
4  COM00005.00  Achinsk Alumina Refinery                  NaN           NaN

  sub_site_other_names facility_type primary_commodity  \
0                  NaN          Mine            Copper
1                  NaN          Mine              Iron
2                  NaN          Mine              Coal
3                  NaN          Mine              Gold
4                  NaN      Refinery        Processing

         commodities_products facility_equipment  production_start  \
0  Copper, Zinc, Gold, Silver        Underground               NaN
1                    Iron ore           Open pit               NaN
2         Sub-bituminous coal                NaN        1,974.0000
3  Copper, Zinc, Gold, Silver                NaN               NaN
4      Alumina, Calcined soda       Sinter plant        1,970.0000

   production_end activity_status  activity_status_year  surface_area_sq_km  \
0             NaN             NaN                   NaN                 NaN
1             NaN             NaN                   NaN                 NaN
2             NaN             NaN                   NaN                 NaN
3             NaN             NaN                   NaN                 NaN
4             NaN             NaN                   NaN                 NaN

   concession_area_sq_km                   country GID_0     GID_1  \
0                    NaN                    Canada   CAN   CAN.3_1
1                 1.6060                     India   IND  IND.16_1
2                    NaN  United States of America   USA  USA.27_1
3                    NaN                Kazakhstan   KAZ        NA
4                    NaN        Russian Federation   RUS  RUS.35_1

         GID_2          GID_3 GID_4 source_id comment  \
0   CAN.3.13_1   CAN.3.13.2_1   NaN  det_1149     NaN
1  IND.16.11_1  IND.16.11.2_1   NaN  det_1307     NaN
2   USA.27.2_1            NaN   NaN  det_1427     NaN
3           NA             NA    NA  det_1123     NaN
4   RUS.35.2_1   RUS.35.2.1_1   NaN  det_1289     NaN

                             geometry
0  MULTIPOINT ((-101.87946 54.77482))
1    MULTIPOINT ((76.20841 14.22353))
2   MULTIPOINT ((-107.0829 45.80531))
3                    MULTIPOINT EMPTY
4    MULTIPOINT ((90.42397 56.23464))

In [5]:
#df = ("../data/raw/Open database on global coal and metal mining/data/ownership.csv")
#df.head()

,id,facility_id,year,owners,operators,source_id,comment
0,1,COM00001.00,2018,Hudbay Minerals Inc (100%),NaN,det_2912,NaN
1,2,COM00005.00,2019,Rusal Plc. (100%),NaN,det_1277,NaN
2,3,COM00006.00,2019,ArcelorMittal S.A. (100%),NaN,det_1218,NaN
3,4,COM00007.00,2018,AngloGold Ashanti (100%),NaN,det_1057,NaN
4,5,COM00009.00,2017,Newmont Mining Corporation (100%),NaN,det_1595,NaN

In [25]:
gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 2413 entries, 0 to 2412
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   facility_id            2413 non-null   str
 1   facility_name          2413 non-null   str
 2   facility_other_names   397 non-null    str
 3   sub_site_name          978 non-null    str
 4   sub_site_other_names   102 non-null    str
 5   facility_type          2413 non-null   str
 6   primary_commodity      2413 non-null   str
 7   commodities_products   2333 non-null   str
 8   facility_equipment     1345 non-null   str
 9   production_start       598 non-null    float64
 10  production_end         117 non-null    float64
 11  activity_status        69 non-null     str
 12  activity_status_year   64 non-null     float64
 13  surface_area_sq_km     15 non-null     float64
 14  concession_area_sq_km  129 non-null    float64
 15  country                2413 non-null   str
 16  GID_0                  2413 non-null   str
 17  GID_1                  1435 non-null   str
 18  GID_2                  1424 non-null   str
 19  GID_3                  790 non-null    str
 20  GID_4                  304 non-null    str
 21  source_id              2413 non-null   str
 22  comment                91 non-null     str
 23  geometry               2413 non-null   geometry
dtypes: float64(5), geometry(1), str(18)
memory usage: 452.6 KB

In [27]:
gdf=gdf[gdf["country"]=="Argentina"]
gdf.head()

,facility_id,facility_name,facility_other_names,sub_site_name,sub_site_other_names,facility_type,primary_commodity,commodities_products,facility_equipment,production_start,production_end,activity_status,activity_status_year,surface_area_sq_km,concession_area_sq_km,country,GID_0,GID_1,GID_2,GID_3,GID_4,source_id,comment,geometry
5,COM00006.00,Acindar,NaN,NaN,NaN,"Smelter, Refinery",Processing,"Steel, rebar, steel bar, steel meshes, wire ro...","Direct reduction iron plant, electric arc furn...",NaN,NaN,NaN,NaN,NaN,NaN,Argentina,ARG,ARG.1_1,ARG.1.111_1,NaN,NaN,det_1219,NaN,MULTIPOINT ((-60.19588 -33.33965))
26,COM00027.00,Altar,NaN,NaN,NaN,Mine,Other mine,"Copper, Gold",NaN,NaN,NaN,Exploration,"2,018.0000",NaN,NaN,Argentina,ARG,ARG.18_1,ARG.18.3_1,NaN,NaN,det_1092,NaN,MULTIPOINT ((-70.46727 -31.48395))
30,COM00031.00,Alumbrera,NaN,NaN,NaN,Mine,Copper,"Gold, Copper, Silver",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Argentina,ARG,ARG.2_1,ARG.2.5_1,NaN,NaN,det_1155,NaN,MULTIPOINT ((-66.60906 -27.33064))
210,COM00211.00,Casposo,NaN,NaN,NaN,Mine,Gold,"Gold, Silver","Underground, Open pit",NaN,NaN,NaN,NaN,NaN,NaN,Argentina,ARG,ARG.18_1,ARG.18.3_1,NaN,NaN,det_1465,NaN,MULTIPOINT ((-69.63001 -31.2108))
228,COM00229.00,Cerro Moro,NaN,NaN,NaN,Mine,Gold,"Gold, Silver, Copper","Open pit, Underground","2,018.0000",NaN,NaN,NaN,NaN,NaN,Argentina,ARG,ARG.20_1,ARG.20.2_1,NaN,NaN,det_1209,NaN,MULTIPOINT ((-66.65373 -48.13037))